export default [
    {
        id: 1,
        title: "Home Creative",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/new/1.jpg",
        new: "yes",
        link: "https://uithemez.com/i/geekfolio/dark/home-creative.html",
        theme: "dark",
    },
    {
        id: 2,
        title: "Personal",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/new/2.jpg",
        new: "yes",
        link: "https://uithemez.com/i/geekfolio/dark/home-personal.html",
        theme: "dark",
    },
    {
        id: 3,
        title: "Home Main",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/m1.jpg",
        new: "yes",
        link: "https://uithemez.com/i/geekfolio/dark/home-main.html",
        theme: "dark",
    },
    {
        id: 4,
        title: "Home Main (Light)",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/m01.jpg",
        new: "yes",
        link: "https://uithemez.com/i/geekfolio/light/home-main.html",
        theme: "light",
    },
    {
        id: 5,
        title: "Corporate",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/1.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/home-corporate.html",
        theme: "dark",
    },
    {
        id: 6,
        title: "Corporate (Light)",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/01.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/light/home-corporate.html",
        theme: "light",
    },
    {
        id: 7,
        title: "One Page",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/2.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/home-onepage.html",
        theme: "dark",
    },
    {
        id: 8,
        title: "One Page (Light)",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/02.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/light/home-onepage.html",
        theme: "light",
    },
    {
        id: 9,
        title: "Digital Agency",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/3.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/home-digital-agency.html",
        theme: "dark",
    },
    {
        id: 10,
        title: "Digital Agency (Light)",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/03.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/light/home-digital-agency.html",
        theme: "light",
    },
    {
        id: 11,
        title: "Freelancer",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/4.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/home-freelancer.html",
        theme: "dark",
    },
    {
        id: 12,
        title: "Freelancer (Light)",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/04.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/light/home-freelancer.html",
        theme: "light",
    },
    {
        id: 13,
        title: "Marketing",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/5.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/home-marketing-agency.html",
        theme: "dark",
    },
    {
        id: 14,
        title: "Marketing (Light)",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/05.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/light/home-marketing-agency.html",
        theme: "light",
    },
    {
        id: 15,
        title: "Creative agency",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/6.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/home-creative-agency.html",
        theme: "dark",
    },
    {
        id: 16,
        title: "Creative agency (Light)",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/06.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/light/home-creative-agency.html",
        theme: "light",
    },
    {
        id: 17,
        title: "Startup Business",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/7.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/home-startup.html",
        theme: "dark",
    },
    {
        id: 18,
        title: "Startup Business (Light)",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/07.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/light/home-startup.html",
        theme: "light",
    },
    {
        id: 19,
        title: "Architecture",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/8.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/home-architecture.html",
        theme: "dark",
    },
    {
        id: 20,
        title: "Architecture (Light)",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/08.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/light/home-architecture.html",
        theme: "light",
    },
    {
        id: 21,
        title: "Parallax Full Screen",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/s1.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/showcase-parallax-slider.html",
        theme: "dark",
        theme2: "showcases",
    },
    {
        id: 22,
        title: "Columns Carousel",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/s4.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/showcase-carousel.html",
        theme: "dark",
        theme2: "showcases",
    },
    {
        id: 23,
        title: "Columns Carousel (Light)",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/s04.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/light/showcase-carousel.html",
        theme: "light",
        theme2: "showcases",
    },
    {
        id: 24,
        title: "Showcase Circle",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/s2.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/showcase-circle-slider.html",
        theme: "dark",
        theme2: "showcases",
    },
    {
        id: 25,
        title: "Showcase Frame",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/s3.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/showcase-frame-slider.html",
        theme: "dark",
        theme2: "showcases",
    },
    {
        id: 26,
        title: "Interactive Links",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/s5.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/dark/showcase-interactive-center-horizontal.html",
        theme: "dark",
        theme2: "showcases",
    },
    {
        id: 27,
        title: "Interactive (Light)",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/s05.jpg",
        new: "no",
        link: "https://uithemez.com/i/geekfolio/light/showcase-interactive-center-horizontal.html",
        theme: "light",
        theme2: "showcases",
    },
    {
        id: 28,
        title: "Coming More",
        coverImg: "https://uithemez.com/i/geekfolio/landing-preview/img/demos/more.jpg",
        new: "no",
        theme: "",
    }
]